// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQ3dAvk98QUB5--lNoincUQxgXqCA0Ug',
    appId: '1:802256833027:web:35ba014ba85777f9cd9c36',
    messagingSenderId: '802256833027',
    projectId: 'yagnik-panchal',
    authDomain: 'yagnik-panchal.firebaseapp.com',
    storageBucket: 'yagnik-panchal.appspot.com',
    measurementId: 'G-NK4318MKX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB53bhALYdLz08hNS01yQYTDKu5cUzVR9E',
    appId: '1:802256833027:android:3f7b7bda1fe30165cd9c36',
    messagingSenderId: '802256833027',
    projectId: 'yagnik-panchal',
    storageBucket: 'yagnik-panchal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B4cvM_b5ZnYSxrBZlBYVwAmwQ9J4gsE',
    appId: '1:802256833027:ios:92e41902b03d48d5cd9c36',
    messagingSenderId: '802256833027',
    projectId: 'yagnik-panchal',
    storageBucket: 'yagnik-panchal.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6B4cvM_b5ZnYSxrBZlBYVwAmwQ9J4gsE',
    appId: '1:802256833027:ios:92e41902b03d48d5cd9c36',
    messagingSenderId: '802256833027',
    projectId: 'yagnik-panchal',
    storageBucket: 'yagnik-panchal.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtQ3dAvk98QUB5--lNoincUQxgXqCA0Ug',
    appId: '1:802256833027:web:91bd3c68af0e0692cd9c36',
    messagingSenderId: '802256833027',
    projectId: 'yagnik-panchal',
    authDomain: 'yagnik-panchal.firebaseapp.com',
    storageBucket: 'yagnik-panchal.appspot.com',
    measurementId: 'G-3H5FTPXZFQ',
  );
}
